spring:
  datasource:
    url: jdbc:h2:file:./data/splitmate;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      platform: h2

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    com.splitmate: DEBUG 